import type { Metadata } from "next";

import { Geist, Geist_Mono, Oswald, Nunito} from "next/font/google";
import "./globals.scss";
import NavBar from "../components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const oswald = Oswald(
  { 
    subsets: ["latin"], 
    weight: "400", 
    variable: "--font-oswald",
  }
);

const nunito = Nunito (
  {
    subsets: ["latin"],
    weight: "400",
    variable: "--font-nunito"
  }
)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${nunito.variable} ${oswald.variable} antialiased`}
      >
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
